---

- name: GRAFANA DOCKER TASK | Ensure That Host Directories Exist
  file:
    path: "{{ item.host_dir }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  notify: "restart_grafana_docker"
  with_items: "{{ grafana_directories }}"

- name: GRAFANA DOCKER TASK | Copy Config Files [from templates]
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ grafana_templates }}"
  notify: "restart_grafana_docker"
  when: grafana_templates is defined and grafana_templates != ""

- name: GRAFANA DOCKER TASK | Copy Config Files [from files]
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ grafana_files }}"
  notify: "restart_grafana_docker"
  when: grafana_files is defined and grafana_files != ""

- name: GRAFANA DOCKER TASK | Start Docker Container
  docker_container:
    name: "{{ grafana_config['docker_opts']['container_name'] }}"
    image: "{{ grafana_config['docker_opts']['image_name'] }}:{{ grafana_config['docker_opts']['image_tag'] }}"
    state: started
    restart_policy: always
    detach: yes
    interactive: yes
    tty: yes
    ports: "{{ grafana_config['docker_opts']['ports'] | default(omit) }}"
    volumes: "{{ grafana_config['docker_opts']['volumes'] | default(omit) }}"
    log_driver: "{{ grafana_config['docker_opts']['log_driver'] | default(omit) }}"
    network_mode: "{{ grafana_config['docker_opts']['network_mode'] | default('bridge') }}"
    networks: "{{ grafana_config['docker_opts']['networks'] | default(omit) }}"
    purge_networks: "{{ grafana_config['docker_opts']['purge_networks'] | default(omit) }}"
    env: "{{ grafana_config['docker_opts']['env_vars'] | default(omit) }}"
