---

# CONSUL
- name: restart_consul_docker
  shell: "docker restart {{ consul_config['docker_opts']['container_name'] }}"

# PROMETHEUS
- name: reload_prometheus
  uri:
    url: "{{ prometheus_url }}/-/reload"
    method: POST
    timeout: 180

- name: restart_prometheus_docker
  shell: "docker restart {{ prometheus_config['docker_opts']['container_name'] }}"

# PROMETHEUS ALERTMANAGER
- name: reload_prometheus_alertmanager
  uri:
    url: "{{ prometheus_alertmanager_url }}/-/reload"
    method: POST
    timeout: 180

- name: restart_prometheus_alertmanager_docker
  shell: "docker restart {{ prometheus_alertmanager_config['docker_opts']['container_name'] }}"

# BLACKBOX EXPORTER
- name: restart_blackbox_exporter_docker
  shell: "docker restart {{ blackbox_exporter_config['docker_opts']['container_name'] }}"

# GRAFANA
- name: restart_grafana_docker
  shell: "docker restart {{ grafana_config['docker_opts']['container_name'] }}"

# NGINX
- name: nginx_check_config_and_reload_docker
  shell: "docker exec -i {{ nginx_config['docker_opts']['container_name'] }} sh -c 'nginx -t && nginx -s reload'"
