---

# CONSUL
- name: restart_consul_docker
  shell: "docker restart {{ consul_config['docker_opts']['container_name'] }}"

# PROMETHEUS
- name: reload_prometheus
  uri:
    url: "{{ prometheus_url }}/-/reload"
    method: POST
    timeout: 180

# PROMETHEUS
- name: reload_prometheus_alertmanager
  uri:
    url: "{{ prometheus_alertmanager_url }}/-/reload"
    method: POST
    timeout: 180

# BLACKBOX EXPORTER
- name: restart_blackbox_exporter_docker
  shell: "docker restart {{ blackbox_exporter_config['docker_opts']['container_name'] }}"

# GRAFANA
- name: restart_grafana_docker
  shell: "docker restart {{ grafana_config['docker_opts']['container_name'] }}"

# NGINX
- name: reload_nginx_docker
  shell: "docker exec -i {{ nginx_config['docker_opts']['container_name'] }} nginx -s reload"
- name: nginx_check_config_and_reload_docker
  shell: "docker exec -i {{ nginx_config['docker_opts']['container_name'] }} nginx -t"
  notify: reload_nginx_docker
